"""
core/ffmpeg_filters.py
Fast FFmpeg-native filter pipeline for Quick Video Editor.

Maps AdjustmentParams → FFmpeg filtergraph string, enabling hardware-accelerated
video export that is 10-50x faster than the Python frame-loop approach.

Filter mapping:
  brightness, contrast     → eq filter
  exposure                 → eq gamma
  highlights, shadows      → curves filter
  sharpness                → unsharp filter
  clarity (local contrast) → unsharp with larger radius + eq boost
  filter_id (LUT)          → lut3d filter using exported .cube file
"""

from __future__ import annotations
import os
import tempfile
import subprocess
from pathlib import Path
from typing import Optional

import numpy as np

from core.params import AdjustmentParams

# ── Constants ─────────────────────────────────────────────────────────────────

import shutil

ROOT_DIR = Path(__file__).parent.parent.resolve()

def find_ffmpeg() -> str:
    # 1. Check in known local / install directories
    candidates = [
        ROOT_DIR / "ffmpeg" / "ffmpeg.exe",
        ROOT_DIR / "ffmpeg.exe",
        Path(r"C:\Program Files\PixClip\ffmpeg\ffmpeg.exe"),
    ]
    for c in candidates:
        if c.exists():
            return str(c)
    # 2. Check in system PATH
    system_path = shutil.which("ffmpeg")
    if system_path:
        return system_path
    # Fallback default path
    return str(ROOT_DIR / "ffmpeg" / "ffmpeg.exe")

FFMPEG_EXE = find_ffmpeg()

# Temp directory for generated .cube files (cached per session)
_CUBE_CACHE_DIR = Path(tempfile.gettempdir()) / "pixclip_cubes"
_CUBE_CACHE_DIR.mkdir(exist_ok=True)

# ── .cube LUT Export ──────────────────────────────────────────────────────────

def export_filter_as_cube(filter_id: str) -> Optional[Path]:
    """
    Builds the 3D LUT from our Python filter catalog and writes it as a
    .cube file. Returns the path, or None if the filter is 'none'/unknown.
    Cached per filter_id for the session.
    """
    if filter_id == "none":
        return None

    cube_path = _CUBE_CACHE_DIR / f"{filter_id}.cube"
    if cube_path.exists():
        return cube_path

    try:
        from core.filters import _get_lut, FILTER_DEFINITIONS
        if filter_id not in FILTER_DEFINITIONS:
            return None

        lut = _get_lut(filter_id)   # shape [N, N, N, 3] float32 BGR in [0,1]
        if lut is None:
            return None

        N = lut.shape[0]

        lines = [
            f"# Generated by PixClip for filter: {filter_id}",
            f"LUT_3D_SIZE {N}",
            "",
        ]
        # .cube format: R changes fastest, B slowest; channels are R G B
        # lut is [B, G, R, BGR_channel] → iterate r, g, b outer
        for bi in range(N):
            for gi in range(N):
                for ri in range(N):
                    b_val, g_val, r_val = lut[bi, gi, ri]
                    lines.append(f"{r_val:.6f} {g_val:.6f} {b_val:.6f}")

        cube_path.write_text("\n".join(lines), encoding="utf-8")
        return cube_path

    except Exception as e:
        print(f"[ffmpeg_filters] Failed to export cube for {filter_id}: {e}")
        return None


def has_color_adjustments(params: AdjustmentParams) -> bool:
    """Returns True if any color, light, tone, or filter parameter is active."""
    return (
        params.exposure != 0.0 or
        params.brightness != 0.0 or
        params.contrast != 0.0 or
        params.light_range != 0.0 or
        params.dark_range != 0.0 or
        params.highlights != 0.0 or
        params.shadows != 0.0 or
        params.lightness != 0.0 or
        params.filter_id != "none"
    )


def generate_adjustment_cube(params: AdjustmentParams, size: int = 33) -> Optional[Path]:
    """
    Generates a 3D LUT .cube file that evaluates the exact color and tonal
    transformations from core.pipeline (exposure, contrast, brightness, tonal range,
    highlights/shadows, lightness, and 3D filter LUT with intensity).
    
    This guarantees 100% mathematical and visual consistency between the
    real-time preview and the exported video without washing out blacks, shifting colors,
    or introducing noise artifacts.
    """
    if not has_color_adjustments(params):
        return None

    import hashlib
    key = (
        f"{params.exposure:.3f}_{params.brightness:.3f}_{params.contrast:.3f}_"
        f"{params.light_range:.3f}_{params.dark_range:.3f}_"
        f"{params.highlights:.3f}_{params.shadows:.3f}_{params.lightness:.3f}_"
        f"{params.filter_id}_{params.filter_intensity:.3f}_{size}"
    )
    cache_hash = hashlib.md5(key.encode("utf-8")).hexdigest()
    cube_path = _CUBE_CACHE_DIR / f"adj_{cache_hash}.cube"
    if cube_path.exists():
        return cube_path

    try:
        from core.pipeline import (
            apply_exposure, apply_brightness_contrast, apply_tonal_range,
            apply_highlights_shadows, _to_lab, apply_lightness, _from_lab
        )
        from core.filters import apply_filter

        N = size
        r = np.linspace(0.0, 1.0, N, dtype=np.float32)
        g = np.linspace(0.0, 1.0, N, dtype=np.float32)
        b = np.linspace(0.0, 1.0, N, dtype=np.float32)
        B, G, R = np.meshgrid(b, g, r, indexing="ij")
        grid = np.stack([B, G, R], axis=-1).reshape(N * N, N, 3)

        img = grid.copy()
        img = apply_exposure(img, params.exposure)
        img = apply_brightness_contrast(img, params.brightness, params.contrast)
        img = apply_tonal_range(img, params.light_range, params.dark_range)
        img = apply_highlights_shadows(img, params.highlights, params.shadows)
        lab = _to_lab(img)
        lab = apply_lightness(lab, params.lightness)
        img = _from_lab(lab)
        if params.filter_id != "none":
            img = apply_filter(img, params.filter_id, params.filter_intensity)

        lut = np.clip(img, 0.0, 1.0).reshape(N, N, N, 3)

        lines = [
            f"# Generated by PixClip adjustment pipeline",
            f"LUT_3D_SIZE {N}",
            "",
        ]
        # .cube format: R changes fastest, G mid, B slowest
        for bi in range(N):
            for gi in range(N):
                for ri in range(N):
                    b_val, g_val, r_val = lut[bi, gi, ri]
                    lines.append(f"{r_val:.6f} {g_val:.6f} {b_val:.6f}")

        cube_path.write_text("\n".join(lines), encoding="utf-8")
        return cube_path

    except Exception as e:
        print(f"[ffmpeg_filters] Failed to generate adjustment cube: {e}")
        return None


# ── Filter Graph Builder ──────────────────────────────────────────────────────

def build_ffmpeg_vf(params: AdjustmentParams) -> str:
    """
    Converts an AdjustmentParams into an FFmpeg -vf filtergraph string.
    Returns 'null' if no adjustments are active.

    Strategy:
      1. Color & Tonal adjustments (exposure, brightness, contrast, highlights,
         shadows, lightness, tonal range, 3D LUT filter) are baked into a
         high-precision 3D LUT (.cube). FFmpeg applies this via lut3d in real-time,
         guaranteeing an exact match with the preview window.
      2. Clarity: applied using a large-radius unsharp on luma only (13:13) with
         gentle local contrast scaling (max 0.35), preventing white haloing.
      3. Sharpness: normalized from the 0–1000 slider range to 0–100, then mapped
         to a fine-radius unsharp (5:5) on luma only with a safe amount (max 0.85),
         eliminating the white dots and ringing artifacts.
    """
    filters: list[str] = []

    # ── 1. Color / Tone / Filter via 3D LUT ──────────────────────────────────
    if has_color_adjustments(params):
        cube_path = generate_adjustment_cube(params)
        if cube_path and cube_path.exists():
            # For Windows FFmpeg, escape colon as '\\:' so FFmpeg filtergraph parses it correctly
            path_str = cube_path.as_posix().replace(":", r"\\:")
            filters.append(f"lut3d=file={path_str}:interp=tetrahedral")

    # ── 2. Clarity (Local contrast enhancement on luma) ──────────────────────
    # Clarity is stored on a 0–1000 scale; normalize to 0–100
    eff_clarity = params.clarity / 10.0 if abs(params.clarity) > 100.0 else params.clarity
    if eff_clarity > 0.0:
        c_norm = max(0.0, min(1.0, eff_clarity / 100.0))
        # Subtle, smooth local contrast boost without edge ringing
        amount = c_norm * 0.35
        filters.append(f"unsharp=13:13:{amount:.3f}:3:3:0")

    # ── 3. Sharpness (Fine edge enhancement on luma) ─────────────────────────
    # Sharpness is stored on a 0–1000 scale; normalize to 0–100
    eff_sharpness = params.sharpness / 10.0 if abs(params.sharpness) > 100.0 else params.sharpness
    if eff_sharpness > 0.0:
        s_norm = max(0.0, min(1.0, eff_sharpness / 100.0))
        # Safe edge sharpening without noise amplification or white speckles
        amount = s_norm * 0.85
        filters.append(f"unsharp=5:5:{amount:.3f}:3:3:0")
    elif eff_sharpness < 0.0:
        # Blur (negative sharpness)
        sigma = min(5.0, abs(eff_sharpness) / 100.0 * 2.5)
        filters.append(f"gblur=sigma={sigma:.2f}")

    return ",".join(filters) if filters else "null"


# ── FFmpeg Quick Export ────────────────────────────────────────────────────────

def build_ffmpeg_command(
    input_path: str,
    output_path: str,
    params: AdjustmentParams,
    preset: str = "fast",
    crf: int = 18,
    audio: bool = True,
) -> list[str]:
    """
    Builds the complete FFmpeg command list for a quick export.

    preset options: ultrafast, superfast, veryfast, faster, fast, medium, slow
    crf: Constant Rate Factor 0 (lossless) to 51 (worst). 18 is near-lossless.
    """
    vf = build_ffmpeg_vf(params)

    cmd = [FFMPEG_EXE, "-y", "-i", input_path]

    if vf != "null":
        cmd += ["-vf", vf]

    # Video encoding
    cmd += [
        "-c:v", "libx264",
        "-preset", preset,
        "-crf", str(crf),
        "-pix_fmt", "yuv420p",
    ]

    # Audio passthrough (fast — no re-encode)
    if audio:
        cmd += ["-c:a", "copy"]
    else:
        cmd += ["-an"]

    cmd.append(output_path)
    return cmd


def run_ffmpeg_export(
    input_path: str,
    output_path: str,
    params: AdjustmentParams,
    preset: str = "fast",
    crf: int = 18,
    progress_callback=None,   # callable(current_frame, total_frames, fps)
    cancelled_check=None,     # callable() → bool
) -> tuple[bool, str]:
    """
    Runs FFmpeg export synchronously in a thread. Parses FFmpeg's stderr for
    progress updates and calls progress_callback periodically.

    Returns (success: bool, message: str).
    """
    if not os.path.exists(FFMPEG_EXE):
        return False, f"FFmpeg not found at: {FFMPEG_EXE}"

    total_frames, fps, has_audio = get_video_duration_frames(input_path)
    cmd = build_ffmpeg_command(input_path, output_path, params, preset, crf, audio=has_audio)

    # Add progress stats output
    cmd_with_stats = []
    insert_idx = cmd.index("-y") + 1
    cmd_with_stats = cmd[:insert_idx] + ["-progress", "pipe:2", "-stats_period", "0.5"] + cmd[insert_idx:]
    # Actually -progress writes to a pipe — simpler to parse stderr -stats
    cmd_with_stats = cmd  # Use regular stderr parsing

    startupinfo = None
    if os.name == "nt":
        startupinfo = subprocess.STARTUPINFO()
        startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW

    try:
        process = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            startupinfo=startupinfo,
            bufsize=1,
        )

        stderr_lines = []
        current_frame = 0

        for line in process.stderr:
            stderr_lines.append(line)
            if cancelled_check and cancelled_check():
                process.kill()
                return False, "Export cancelled."

            # Parse progress: "frame=  42 fps= 24 ..."
            if line.startswith("frame="):
                parts = line.split()
                for i, p in enumerate(parts):
                    if p == "frame=" or (p.startswith("frame=") and len(p) > 6):
                        try:
                            val = p.split("=")[1] if "=" in p else parts[i + 1]
                            current_frame = int(val.strip())
                        except Exception:
                            pass
                        break
                # Extract fps
                fps_val = None
                for p in parts:
                    if p.startswith("fps="):
                        try:
                            fps_val = float(p.split("=")[1])
                        except Exception:
                            pass
                if progress_callback:
                    progress_callback(current_frame, total_frames or 0, fps_val or 0)

        process.wait()

        if process.returncode == 0:
            return True, "Export completed successfully."
        else:
            stderr_text = "".join(stderr_lines[-30:])  # last 30 lines for error context
            return False, f"FFmpeg failed (code {process.returncode}):\n{stderr_text}"

    except Exception as e:
        return False, f"Export error: {e}"


def get_video_duration_frames(input_path: str) -> tuple[int, float, bool]:
    """
    Uses FFmpeg to get total frame count, fps, and whether it has an audio stream.
    Returns (frame_count, fps, has_audio).
    """
    if not os.path.exists(FFMPEG_EXE):
        return 0, 0.0, False
    startupinfo = None
    if os.name == "nt":
        startupinfo = subprocess.STARTUPINFO()
        startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW
    try:
        result = subprocess.run(
            [FFMPEG_EXE, "-i", input_path],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            startupinfo=startupinfo,
            timeout=10,
        )
        # Parse: "Stream #0:0: Video: ..., 30 fps, ..."
        # Duration: 00:01:23.45
        import re
        duration_s = 0.0
        fps = 0.0
        has_audio = False
        dur_match = re.search(r"Duration:\s*(\d+):(\d+):(\d+(?:\.\d+)?)", result.stderr)
        if dur_match:
            h, m, s = dur_match.groups()
            duration_s = int(h) * 3600 + int(m) * 60 + float(s)
        fps_match = re.search(r"(\d+(?:\.\d+)?)\s*fps", result.stderr)
        if fps_match:
            fps = float(fps_match.group(1))
        frame_count = int(duration_s * fps) if fps > 0 else 0
        
        if re.search(r"Stream #.*Audio:", result.stderr):
            has_audio = True
            
        return frame_count, fps, has_audio
    except Exception:
        return 0, 0.0, False
